# Generated by Django 6.0.3 on 2026-04-15 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0002_remove_category_icon_name_category_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_name',
            field=models.CharField(default='LayoutGrid', max_length=50),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='Petite description de la palette')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='domains.category')),
            ],
            options={
                'verbose_name': 'Sous-Domaine',
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ResourceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(help_text='La description qui apparaîtra à côté de la photo')),
                ('url', models.URLField(help_text='Le lien vers le site officiel')),
                ('image', models.ImageField(blank=True, null=True, upload_to='resources/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='domains.subcategory')),
            ],
            options={
                'verbose_name': 'Lien de Ressource',
            },
        ),
    ]
