# Generated by Django 6.0.4 on 2026-04-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0003_category_icon_name_subcategory_resourcelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon_name',
            field=models.CharField(default='grid', max_length=50),
        ),
    ]
