# Generated by Django 6.0.3 on 2026-04-13 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0001_initial'),
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='domains.category'),
        ),
        migrations.RemoveField(
            model_name='link',
            name='description',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
