# Generated by Django 6.0.4 on 2026-04-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Publicité', 'verbose_name_plural': 'Publicités'},
        ),
        migrations.AlterField(
            model_name='ad',
            name='image_url',
            field=models.URLField(verbose_name="URL de l'image"),
        ),
        migrations.AlterField(
            model_name='ad',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='ad',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Sous-titre'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Titre'),
        ),
    ]
