# Generated by Django 5.2.1 on 2026-03-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('user', 'Utilisateur')], default='admin', max_length=10),
        ),
    ]
